Repository bachelor-gruppe-04/chess-digitization, pull requests merged in 2025-05, with the labels that each got.

#60 Feature/50 ml app
  backend/logic/api/entity/camera.py
  backend/logic/api/entity/detector.py
  backend/logic/api/routes/video_routes.py
  backend/logic/api/services/board_service.py
  backend/logic/api/services/board_storage.py
  backend/logic/machine_learning/board_state/map_pieces.py
  backend/logic/machine_learning/run_video.py
  backend/logic/view/app_view.py
  backend/logic/view/progress_bar_view.py
  backend/logic/view/reset_specific_board_view.py
Labels: enhancement

#61 Feature/54 resizeable camera view
  frontend/index.html
  frontend/src/components/camera/camera.css
  frontend/src/components/camera/camera.tsx
Labels: enhancement

#64 Fen and stockfish
  backend/logic/analysis/chess_analysis.py
  backend/logic/api/entity/ml_simulator.py
  backend/logic/api/services/board_storage.py
  frontend/src/components/chessboard/chessboard.tsx
  frontend/src/components/stockfish/evalbar.css
  frontend/src/components/stockfish/evalbar.tsx
  frontend/src/components/stockfish/stockfish.tsx
  frontend/src/pages/boardview/boardview.tsx
Labels: enhancement

#67 Feature/63 initialize number of boards
  backend/logic/api/config.py
  backend/logic/api/entity/board.py
  backend/logic/api/entity/board_factory.py
  backend/logic/api/entity/camera.py
  backend/logic/api/entity/detector.py
  backend/logic/api/entity/ml_simulator.py
  backend/logic/api/entity/test_board.py
  backend/logic/api/routes/admin_routes.py
  backend/logic/api/routes/video_routes.py
  backend/logic/api/routes/websocket_routes.py
  backend/logic/api/services/board_service.py
  backend/logic/api/services/board_storage.py
  backend/logic/machine_learning/run_video.py
  backend/logic/view/app_view.py
  backend/logic/view/progress_bar_view.py
  backend/logic/view/reset_specific_board_view.py
  backend/main.py
  backend/requirements-test.txt
  backend/requirements.txt
  frontend/src/App.tsx
  frontend/src/components/camera/camera.tsx
  frontend/src/components/chessboard/chessboard.tsx
  frontend/src/components/stockfish/evalbar.tsx
  frontend/src/pages/boardview/boardview.tsx
  frontend/src/pages/tournamentview/tournamentview.css
  frontend/src/pages/tournamentview/tournamentview.tsx
Labels: enhancement

#70 Feature/66 reset state board
  backend/logic/api/entity/board.py
  backend/logic/api/services/board_service.py
  backend/logic/machine_learning/board_state/find_FEN.py
  backend/logic/machine_learning/board_state/map_pieces.py
  backend/logic/machine_learning/detection/run_detections.py
  backend/logic/machine_learning/game/game.py
  backend/logic/machine_learning/game/game_store.py
  backend/logic/machine_learning/run_video.py
  backend/logic/view/app_view.py
Labels: bug, enhancement

#75 Feature/74 type safety
  backend/README.md
  backend/logic/api/entity/board_factory.py
  backend/logic/api/entity/detector.py
  backend/logic/api/entity/ml_simulator.py
  backend/logic/api/entity/test_board.py
  backend/logic/api/routes/admin_routes.py
  backend/logic/api/services/board_service.py
  backend/logic/view/app_view.py
  backend/logic/view/ctk_type_enum.py
  backend/logic/view/progress_bar_view.py
  backend/logic/view/reset_specific_board_view.py
  frontend/src/hooks/useEvaluation.ts
Labels: documentation, enhancement
